server:
  port: 8080

spring:
  application:
    name: loyalty-redemption-portal

  datasource:
    url: jdbc:h2:mem:loyaltydb
    driver-class-name: org.h2.Driver
    username: sa
    password: 

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com.loyaltyportal: INFO
    org.springframework.web: INFO